### ISSUE TITLE
Diagnose which files and why Hook is slower from around 80% to 100%

### ISSUE THREAD

**Issue by PonteIneptique** [OpenGreekAndLatin/csel-dev#233] opened 2015-12-09 11:11 UTC
Right now, tests coming from CSEL-DEV are super slow. Part of it might be //div stuff, but we need a real diagnose. @sonofmun proposed himself last week for this specific task.

**Comment by sonofmun** [comment] 2015-12-09 11:26
@PonteIneptique What tests should be happening in the 80%-100% range.  It seems to really stick at about 97% and stay there for several minutes.  Any insight here as to the tests I should be looking at would be appreciated.

**Comment by PonteIneptique** [comment] 2015-12-09 12:07
Try to run it locally, and see where it hangs, would be the first thing I'd do. If this is not enough, we might need to change a little the code for timing purpose

**Comment by annettegessner** [comment] 2015-12-09 15:38
Sorry for keeping hook so busy! I kept our routine of creating one push per file altered, but as we see, this might not be the best solution right now. For me it's kind of "stopping" at 95% for a long time.
How do you think we should proceed?

**Comment by PonteIneptique** [comment] 2015-12-09 15:40
We need to debug this situation. Keep working as you do, or limit pushes (*ie* push only at the end of the day. One push != one commit :) ) but I think it's ok. We can't avoid this situation for the moment.

**Comment by sonofmun** [comment] 2015-12-10 08:05
Removing extraneous // seems to have helped quite a bit.  We can keep an eye on it to see whether it really does run faster now and only close this issue when we know the problem is solved.

**Comment by sonofmun** [comment] 2016-01-07 09:03
It now runs very quickly up to 99%.  At 99% it hangs for a while.  I don't know if this means it is writing the files or what exactly the last step in the process is.  I doubt this has anything to do with the files themselves, however.  What do you thing @PonteIneptique ?

**Comment by PonteIneptique** [comment] 2016-01-07 09:08
I do not know. Is it possible there is some super large file at the end ?

**Comment by sonofmun** [comment] 2016-01-07 09:43
I doubt this is the problem.  It runs up to 99% in less than a minute and then it hangs at 99% for several minutes.  I can't believe there is a file that is so much larger than all the other files combined.
Now, it could be that there are still // somewhere in the refsDecls and that is causing the problems.  But I have removed all of the unnecessary ones so perhaps leaving it as it is should be OK.

**Comment by PonteIneptique** [comment] 2016-01-07 09:45
Could be an unknown bottleneck. Right now, csel-dev is the only repository with that much passing files. We'll probably see what happens with the next one.

**Comment by PonteIneptique** [comment] 2016-01-07 09:46
Could you tell me if running the test locally has the same issue ?

**Comment by sonofmun** [comment] 2016-01-07 10:04
I've got it running now and printing to the console locally.  I will let you know where it hangs.

**Comment by sonofmun** [comment] 2016-01-07 10:35
I found the problem file (stoa0171.stoa009.opp-lat1.xml) and have changed the refsDecl, removing the // and the @subtype declarations in the xpath.  It still finds the same number of citations at each level, so everything should be fine now.  Will do a PR and check it.

**Comment by sonofmun** [comment] 2016-01-07 10:40
This now seems to run pretty smoothly.  Locally, there are still files that run slowly, but it finishes in good time.  Closing this issue.

**Closed by sonofmun** 2016-01-07 10:40 UTC
