### ISSUE TITLE
Add ant-build

### ISSUE THREAD

**Issue by PonteIneptique** [OpenGreekAndLatin/csel-dev#269] opened 2016-01-07 09:16 UTC
Good assignment for you Matt :D 
Could you add the ant/eXist required data ?

**Comment by sonofmun** [comment] 2016-01-07 09:36
Where is the tutorial for this again?

**Comment by PonteIneptique** [comment] 2016-01-07 09:40
Example would be there. Not sure this is the best (It needs rewriting)

http://capitains.github.io/pages/guidelines.html

But you could probably just copy / edit PerseusDL/canonical-latinLit ;)

**Comment by sonofmun** [comment] 2016-01-07 10:55
I have added the build.xml file and the collection.xconf file manually, using the templates from canonical-latinlit but the build fails when I do ```ant build``` with the following error.

```
Buildfile: /home/matt/OpenMigne/csel-dev/build.xml

copy:
     [copy] Copying 1 file to /home/matt/OpenMigne/csel-dev/pre-build
     [copy] Copying /home/matt/OpenMigne/csel-dev/collection.xconf to /home/matt/OpenMigne/csel-dev/pre-build/collection.xconf
     [copy] Copied 1 empty directory to 1 empty directory under /home/matt/OpenMigne/csel-dev/pre-build

include:

BUILD FAILED
/home/matt/OpenMigne/csel-dev/build.xml:22: javax.script.ScriptException: ReferenceError: "importClass" is not defined in <eval> at line number 13
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.util.ReflectUtil.invoke(ReflectUtil.java:108)
        at org.apache.tools.ant.util.ReflectWrapper.invoke(ReflectWrapper.java:81)
        at org.apache.tools.ant.util.optional.JavaxScriptRunner.evaluateScript(JavaxScriptRunner.java:103)
        at org.apache.tools.ant.util.optional.JavaxScriptRunner.executeScript(JavaxScriptRunner.java:67)
        at org.apache.tools.ant.taskdefs.optional.Script.execute(Script.java:52)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: <eval>:13 ReferenceError: "importClass" is not defined
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
        at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1432)
        at jdk.nashorn.internal.scripts.Script$\^eval\_.:scopeCall(<eval>)
        at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:13)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
        ... 30 more

Total time: 0 seconds
```

**Comment by sonofmun** [comment] 2016-01-07 11:03
I expect the problem is that I haven't done this with the eXide app.  I will take care of that today and see if it fixes the problem.  I will need to watch the tutorial to do this.

**Comment by PonteIneptique** [comment] 2016-01-07 11:08
It is a java compatibility issue. Test with Java 7

**Comment by sonofmun** [comment] 2016-01-07 11:25
Done.  The build worked.  Adding the files to a PR.

**Comment by sonofmun** [comment] 2016-01-07 11:25
Oops, I shouldn't have closed the issue before the PR is merged.

**Closed** 2016-01-07 17:12 UTC
